### ISSUE TITLE
RCS Inverted when Placed

### ISSUE THREAD

**Issue by NaethKerman** [CobaltWolf/Bluedog-Design-Bureau#1197]
![Screenshot (140)](https://user-images.githubusercontent.com/87446296/162645093-1474aad0-82f8-4a40-8e7d-1825d77bde59.png)
This is what happens when I place some of the new Kane RCS Thrusters. Not all of them do this.
Also, the RCS thruster selected, (I believe) should only have three RCS thrusters instead of four.

**Comment by CobaltWolf** [comment]
When did you last update the mod? I think that part was broken back in February but it seems fixed?

**Comment by NaethKerman** [comment]
Updated it pretty recently.

**Comment by CobaltWolf** [comment]
Yeah, someone else is having the same issue. I could've sworn I fixed it but I guess not

**Comment by CobaltWolf** [comment]
Should be fixed now!

**Comment by NaethKerman** [comment]
Um, It's not completely fixed. Just realized the 45 degrees RCS triad and quad still have this issue

**Comment by zorg2044** [comment]
Tested them all, there are 3 problem parts remaining

![screenshot245](https://user-images.githubusercontent.com/39182212/167272750-974e2071-613c-4f2b-845a-
![screenshot247](https://user-images.githubusercontent.com/39182212/167272754-dfdcf856-a976-47cb-80db-7f92c611ea86.png)
2d2029c46858.png)
![screenshot246](https://user-images.githubusercontent.com/39182212/167272753-74cca7a3-13a0-48e3-a7bb-6ac76df39cc6.png)

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/6211fcabaf0f1cb8ed2cb7d94f34f01624217bfa
