### ISSUE TITLE
[ModuleB9PartSwitch 'meshSwitchLength'] Cannot find parent module with id 'fuelSwitch'

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [CobaltWolf/Bluedog-Design-Bureau#1318]
[LOG 20:14:32.770] [Part bluedog.Saturn.AJ260.Inline] [ModuleB9PartSwitch 'meshSwitchLength'] Switched subtype to 19m Solid
[LOG 20:14:32.949] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:33.022] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:33.136] [FAR v0.16.1.0]: Voxel Element CrossSection Area: 0.00306364797752344
[LOG 20:14:33.165] [FAR v0.16.1.0]: Std dev for smoothing: 3 voxel total vol: 42.3934051626953 filled vol: 29.320660136555
[LOG 20:14:33.301] [FAR v0.16.1.0]: Voxelization Time (ms): 278
[LOG 20:14:34.318] deleting part bluedog.Saturn.AJ260.Inline
[LOG 20:14:35.017] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:35.121] [FAR v0.16.1.0]: Voxel Element CrossSection Area: 0.00306364797752344
[LOG 20:14:35.152] [FAR v0.16.1.0]: Std dev for smoothing: 3 voxel total vol: 42.3934051626953 filled vol: 29.320660136555
[LOG 20:14:35.180] [FAR v0.16.1.0]: Voxelization Time (ms): 162
[ERR 20:14:35.871] [ERROR] [Part bluedog.Saturn.S1C.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Cannot find parent module with id 'fuelSwitch'

[WRN 20:14:35.967] [ModuleTweakableFuelPump] No resource named LiquidFuel found in part bluedog.Saturn.S1C.Tank; skipping.
[WRN 20:14:35.967] [ModuleTweakableFuelPump] No resource named  Oxidizer found in part bluedog.Saturn.S1C.Tank; skipping.
[LOG 20:14:35.978] [RealFuels.ModuleFuelTankRF] bluedog.Saturn.S1C.Tank Area Calcs: DragCube: 763.57 | TotalSpherical: 305.59 | SubTankSpherical: 0.00
[LOG 20:14:35.978] [RealFuels.ModuleFuelTankRF] bluedog.Saturn.S1C.Tank.totalTankArea = 305.59
[LOG 20:14:35.990] [Part bluedog.Saturn.S1C.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Switched subtype to S-1C
[LOG 20:14:36.862] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:36.958] [FAR v0.16.1.0]: Voxel Element CrossSection Area: 0.00306364797752344
[LOG 20:14:36.992] [FAR v0.16.1.0]: Std dev for smoothing: 3 voxel total vol: 42.3934051626953 filled vol: 29.320660136555
[LOG 20:14:37.116] [FAR v0.16.1.0]: Voxelization Time (ms): 253
[LOG 20:14:37.129] deleting part bluedog.Saturn.S1C.Tank
[ERR 20:14:38.921] [ERROR] [Part bluedog.Saturn.S2.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Cannot find parent module with id 'fuelSwitch'

[LOG 20:14:39.015] [Part bluedog.Saturn.S2.Tank] [ModuleB9PartSwitch 'textureSwitchPaint'] Switched subtype to Saturn V
[LOG 20:14:39.015] [Part bluedog.Saturn.S2.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Switched subtype to S-II
[LOG 20:14:39.041] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:39.123] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:39.151] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:39.250] [FAR v0.16.1.0]: Voxel Element CrossSection Area: 0.00306364797752344
[LOG 20:14:39.282] [FAR v0.16.1.0]: Std dev for smoothing: 3 voxel total vol: 42.3934051626953 filled vol: 29.320660136555
[LOG 20:14:39.309] [FAR v0.16.1.0]: Voxelization Time (ms): 158
[LOG 20:14:39.797] deleting part bluedog.Saturn.S2.Tank
[ERR 20:14:40.240] Material doesn't have a texture property '_BumpMap'

[LOG 20:14:40.330] [Part bluedog.Saturn.S2.wetWorkshop] [ModuleB9PartSwitch 'meshSwitchLab'] Switched subtype to Lab
[LOG 20:14:40.337] [Part bluedog.Saturn.S2.wetWorkshop] [ModuleB9PartSwitch 'textureSwitchPaint'] Switched subtype to Saturn V
[LOG 20:14:41.165] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:41.264] [FAR v0.16.1.0]: Voxel Element CrossSection Area: 0.00306364797752344
[LOG 20:14:41.300] [FAR v0.16.1.0]: Std dev for smoothing: 3 voxel total vol: 42.3934051626953 filled vol: 29.320660136555
[LOG 20:14:41.346] [FAR v0.16.1.0]: Voxelization Time (ms): 181
[LOG 20:14:42.163] deleting part bluedog.Saturn.S2.wetWorkshop
[ERR 20:14:42.807] [ERROR] [Part bluedog.Saturn.S4B.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Cannot find parent module with id 'fuelSwitch'

[LOG 20:14:42.894] [Part bluedog.Saturn.S4B.Tank] [ModuleB9PartSwitch 'textureSwitchPaint'] Switched subtype to 500 Series
[LOG 20:14:42.894] [Part bluedog.Saturn.S4B.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Switched subtype to S-IVB
[LOG 20:14:43.073] [FAR v0.16.1.0]: Updating 未命名飞船
[LOG 20:14:43.186] [FAR v0.16.1.0]: Voxel Element CrossSection Area: 0.00306364797752344
[LOG 20:14:43.218] [FAR v0.16.1.0]: Std dev for smoothing: 3 voxel total vol: 42.3934051626953 filled vol: 29.320660136555
[LOG 20:14:43.260] [FAR v0.16.1.0]: Voxelization Time (ms): 187
[LOG 20:14:43.724] deleting part bluedog.Saturn.S4B.Tank
[ERR 20:14:44.808] [ERROR] [Part bluedog.Saturn.S4B.Tank] [ModuleB9PartSwitch 'meshSwitchLength'] Cannot find parent module with id 'fuelSwitch'

**Comment by Rodg88** [comment]
Can you upload your whole ksp.log somewhere and link it here?

**Comment by GIS-PuppetMaster** [comment]
> Can you upload your whole ksp.log somewhere and link it here?

I have seen an error hint inside the game, that said B9PartSwitch has some problems with ModularFuelTank, I guess the Real Fuel may be the reason. Here is my log:
[https://1drv.ms/u/s!Ao4ZI6lp9rIGubt3cA5H3iknsr2VtA?e=4WLUZF](url)

**Comment by GIS-PuppetMaster** [comment]
> Can you upload your whole ksp.log somewhere and link it here?

I notice that if a Saturn tank uses LqdHydrogen and has the `parentID = fuelSwitch` in its cfg, then I can't use either B9PartSwitch or RealFuel to switch fuel types. If it uses LiquidFuel then I can at least use RealFuel to switch fuel types.

**Comment by Rodg88** [comment]
Yeah it is to do with RealFuels patching. when RF was installed the main B9 fuel switch doesn't get added, but some tanks still referenced the B9 fuel switch module. the dev branch of bdb should have this fixed now

**Comment by GIS-PuppetMaster** [comment]
> 

I tried the dev branch and I still can't switch fuel type

**Comment by GIS-PuppetMaster** [comment]
> Yeah it is to do with RealFuels patching. when RF was installed the main B9 fuel switch doesn't get added, but some tanks still referenced the B9 fuel switch module. the dev branch of bdb should have this fixed now

The error is gone using the dev branch version, but I still can't use RealFuel to switch fuel type, I found that the RealFuel works only for those tanks that have LiquidFuel in their config.
